### ISSUE TITLE
Suggest and implement interface

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/indesign#1]
[The comment which was here before has been moved to #6]

This #1 issue is about implementing the appropriate interface for the plug-in:
- There should probably be a window/panel where all parameters needed to create the links with the Librelio syntax could be entered.
- It should be possible to open this window/panel when editing a link in InDesign, or creating a new one
- There might be a button or menu somewhere to create new Librelio links

We are expecting suggestions from experienced contributors here.

cc @kinanu

**Comment by kinanu** [comment]
Hi,
I have seen your project on Freelancer.com
If I understand correctly, you want an InDesign plugin which will export the current document (png's/jpg's of all pages) and then opens your htmlviewer to show the exported pages ...
- Do you need a Windows and Mac (C++) plugin for InDesign? Which version(s) do you want to support (CS6, CC, InDesign Server, ...)?
- Is it ok to add an extra "Export" format (Librelio) to the InDesign desktop "File > Export" menu or do you want an extra panel with an export button? 
- Should the preview be opened automatically in a browser window (outside InDesign) or in a webview (inside InDesign)? Or is it ok to export to the "Librelio" format and save it on the users disk. Can the user browse to the directory and start your htmlviewer from there?
- I do not understand the requirements concerning issue #2 and #3: is it the same like issue #1? Export the document and preview the slideshow or video in your htmlviewer?

**Comment by libreliodev** [comment]
@kinanu Thank you for the questions.

> Do you need a Windows and Mac (C++) plugin for InDesign? Which version(s) do you want to support (CS6, CC, InDesign Server, ...)?

Mac & PC, CS5 if possible.

> Is it ok to add an extra "Export" format (Librelio) to the InDesign desktop "File > Export" menu or do you want an extra panel with an export button?

We are opened to suggestions.

> Should the preview be opened automatically in a browser window (outside InDesign) or in a webview (inside InDesign)? Or is it ok to export to the "Librelio" format and save it on the users disk. Can the user browse to the directory and start your htmlviewer from there?

We would probably prefer a webview, if possible. 

>  I do not understand the requirements concerning issue #2 and #3: is it the same like issue #1? Export the document and preview the slideshow or video in your htmlviewer?

As described in #2 and #3, we use a specific syntax for enhancements such as videos or slide shows. We need to make it easy for users not knowing this syntax to add videos or slide shows, by sing check boxes or radio buttons.

**Comment by libreliodev** [comment]
@kinanu Thank you for your new questions by e-mail

> The plugin should be able to preview the document in your htmlviewer (as an interactive PDF). So the user needs to have your htmlviewer installed on his/her computer and when generating the preview, the interactive pdf should be copied to the directory of the htmlviewer and be visible within a webview in InDesign.

Ideally, we should embed all the javascript viewer code into the plug in, so that the user does not have to install it. Alternatively, if simpler, we could implement a native video and slide show viewer in the plug in (see issues #4 and #5)

> It should be made easier for the user to enter the hyperlinks that can be put on images and movies in InDesign.

This is perfectly correct

**Comment by libreliodev** [comment]
@kinanu Just to clarify

> If I understand correctly, you want an InDesign plugin which will export the current document (png's/jpg's of all pages) ...

The export format is pdf, not png or jpg. See #7

> ... and then opens your htmlviewer to show the exported pages

We are not sure about the html viewer ( #6 ) vs native viewer inside the plug in (#4 and #5). We are opened to suggestions from experienced contributors.

**Comment by libreliodev** [comment]
@kinanu Thank you for uploading initial version. We will test later today or tomorrow.

Is this version of the plug-in going to be compatible with earlier versions of InDesign? Do we need to download other sdk versions to ensure this compatibility?

**Comment by kinanu** [comment]
This version will only work with InDesign CS5. Each version needs to be compiled with its SDK version.

**Comment by libreliodev** [comment]
@kinanu Thanks for your answer. It turns out that it’s going to be very complicated to manage different versions of the plug in. So, we’d better start with the latest InDesign version. Can you upgrade the code? Please contact us privately if needed.

**Comment by kinanu** [comment]
Ok. I will use the SDK for InDesign CC 2014 (and keep the CS5 version). Please bare in mind that setting this up will take some extra time. I will try to do this within the estimated time and budget. The ideal scenario would be that all versions (CS5, CS5.5, CS6, CC, CC2014, …) are supported.

**Comment by libreliodev** [comment]
Thank you, sorry for this change, this is a new platform for us and we are in the learning phase.
If you need extra budget, just  let me know in advance please.
Many thanks again.

**Comment by kinanu** [comment]
Hi Emmanuel,

No problem. Pleas add an extra $50 to the budget. That should compensate for the extra work (= adding the CC 2014 SDK setup).

**Comment by libreliodev** [comment]
Sure, many thanks.

**Comment by libreliodev** [comment]
@kinanu Thanks for updating the project.

We have tried opening the project in XCode, but there are missing resources (see screenshot). Is it possible to add them to the repository? If there are special instructions, can you put them in the Wiki?

![screen shot 2014-08-11 at 22 09 50](https://cloud.githubusercontent.com/assets/3107052/3882062/c5c6671c-2193-11e4-8c12-735693526b8c.png)

**Comment by kinanu** [comment]
Hi,

Have you downloaded and installed the InDesign 2014 CC SDK? The same instructions as for the CS5 version are valid only you have to change the folder name of the sdk to id10sdk. I will update the wiki. 

Kind Regards,

Geert.

**Comment by libreliodev** [comment]
@kinanu Thank you for your quick answer. We are still waiting for an answer from Adobe after filling the form required to download the 2014 CC SDK. Is it possible to add the required files to the project, it will be more simple anyway?

**Comment by kinanu** [comment]
The zipped sdk is over 200MB and unzipped over 900MB. Shall I put the sdk zip in my dropbox folder and send you the link. I can do that this evening?

**Comment by libreliodev** [comment]
@kinanu Thanks for uploading the sdk. We just tested the first version, here are our comments, please let us know if we missed or misunderstood something

> There should probably be a window/panel where all parameters needed to create the links with the Librelio syntax could be entered.

This has been implemented, and will be completed when dealing with #2 and #3

> It should be possible to open this window/panel when editing a link in InDesign, or creating a new one

This has not yet been implemented. 

> There might be a button or menu somewhere to create new Librelio links

This has not yet been implemented

cc @libreliorip

**Comment by kinanu** [comment]
I still need to do some work before the first version is finished. I will try to get a working version before sunday evening.

**Comment by kinanu** [comment]
Hi Emmanuel,

I have pushed a limited working version to your repository. I still need to do some work.

**Comment by libreliodev** [comment]
@kinanu Thank you for the report. 

One question please: is it possible to make the plug-in easily installable using the extension manager, as other plug-ins such as http://ajarproductions.com/pages/products/in5/download.php ?

**Comment by libreliodev** [comment]
@kinanu 

Here is the current version of the panel that we see in InDesign
![screen shot 2014-08-22 at 11 09 29](https://cloud.githubusercontent.com/assets/3107052/4008854/8854aa00-29dc-11e4-875d-e447857a0a75.png)

**Comment by kinanu** [comment]
Ok. A quick explanition so you can start testing (I will put this in the wiki):
The controls on the panel are enabled when you select a slideshow item (multistate object). When you select a movie only the first two controls are enabled. You can specify the url and use the controls to build the hyperlink. Let me know if it works for you.

**Comment by libreliodev** [comment]
@kinanu Thanks for the explanation. It seems that we have different visions regarding the basic interface. 

From what I have understood, your suggestion (and what you have started developing) is that in order to create an enhancement (video or slideshow), the user must  first "place" a video (or multistate object) into the document. 

Our initial specification mentioned that:

> There might be a button or menu somewhere to create new Librelio links

The method you are suggesting is different. This might be a good idea, but I see 2 difficulties:
- when placing an object, the object preview is shown inside the document (from what I have understood). This may be confusing when the video or slide show is not "auto start". In this case, it should not appear on the end user screen directly, but there should be a button or something  to start the video or slide show. Now, from the graphic designer perspective, I think it's confusing that the video (or slide show) is displayed on the document whereas only a "button" should be displayed, to reflect the end user experience
- the current project is about slide shows and videos, but we have other enhancements. For these other enhancement, the "place" method may not work, because the object type does not exist or is not supported. For example, we support "maps" or "rss" enhancements. I guess there is no "place" option for such objects.

The initial specifications also mentioned that;

> It should be possible to open this window/panel when editing a link in InDesign, or creating a new one

It seems that with your method, it will not be possible to "edit" links created manually.

Again, we are opened to discussions. Feel free to comment if you disagree. 

cc @libreliorip

**Comment by kinanu** [comment]
@librelio: I think your idea is good because it is even more user-friendly (but more complex to develop). I can add a “Add slideshow” and “Add movie” menu item to the panel. The “Add slideshow” action will then open a file browser in which the user can select a folder which contains the images for the slideshow. Once the user selects a folder the user can place the images on the document and the multi-state object is automatically created. The same can be done for the “Add movie” action. If I understand correctly, you want to show a play button (or maybe something else to show that it is a slideshow or movie object) above the (slideshow) image or movie in InDesign when it is created thru the menu actions? Is this correct? Do you just want to show this button or do you want this button to be functional (clicking on it will start the slideshow/movie in InDesign, this will require a lot of work). Maybe it is better for the first version of the plugin to leave out the preview stuff and only add information to the graphic frame to show that it is a slideshow, movie, map, rss or … (I will create a mockup and attach it later) Again, I will need more time and budget for this. Do you want me to finish the installer first or should I start investigating the “Add slideshow/movie” actions?

**Comment by kinanu** [comment]
See mockup below ...
![mockup](https://cloud.githubusercontent.com/assets/1545390/4020655/d8fe120e-2ac5-11e4-9201-e1d54f13e9e6.png)

**Comment by libreliodev** [comment]
@kinanu Thanks for your suggestions and comments. We will provide a detailed answer later. Can you finish the installer (issue #8)?

**Comment by libreliodev** [comment]
@kinanu Sorry for this late answer

>  I can add a “Add slideshow” and “Add movie” menu item to the panel.

Yes, you can do this, but I think it would probably be better to have a generic menu "Add Librelio Enhancement", and then to choose the enhancement type (right now we only have Videos and Slide Shows, but we'll add more later). I believe the right way to do it is the way "regular" links are created in InDesign. Instead of "Link to", we would have "Enhancement type", and below we would have the various options that have already been developed.

![screen shot 2014-09-01 at 08 14 32](https://cloud.githubusercontent.com/assets/3107052/4105436/108e7840-31aa-11e4-9531-a4c4ccc96429.png)

>  If I understand correctly, you want to show a play button (or maybe something else to show that it is a slideshow or movie object) above the (slideshow) image or movie in InDesign when it is created thru the menu actions? Is this correct?

No,we do not always "want" to show a play button. This depends on wether or not `waplay=auto`. See issue #10 for more details.

> Do you just want to show this button or do you want this button to be functional (clicking on it will start the slideshow/movie in InDesign, this will require a lot of work)

We will implement a preview mode later (see #5 and #4)

> Maybe it is better for the first version of the plugin to leave out the preview stuff and only add information to the graphic frame to show that it is a slideshow, movie, map, rss or … (I will create a mockup and attach it later) Again, I will need more time and budget for this.

Yes, for the first version, we just need to implement a way to create a new enhancement. Again, subject to your comments, the best option is probably to do it in a similar way as when creating regular links.

**Comment by libreliodev** [comment]
@kinanu 

Here are the elements missing at this time, based on the original spec

> It should be possible to open this window/panel when editing a link in InDesign, or creating a new one

Currently, it does not seem to be possible to edit a link using our panel, only links created with the panel can be edited

> There might be a button or menu somewhere to create new Librelio links

There is no such button or menu

**Comment by kinanu** [comment]
> Currently, it does not seem to be possible to edit a link using our panel, only links created with the panel can be edited.

What "link" do you mean? Can you give an example? Can you attach an InDesign file which contains a link that should be editable?

> There might be a button or menu somewhere to create new Librelio links

What should be the behaviour of the menu item? You say "create new Librelio links" but what should be the action in InDesign?

**Comment by libreliodev** [comment]
@kinanu Sorry for the late answer.

> What "link" do you mean? Can you give an example? Can you attach an InDesign file which contains a link that should be editable?

By link, I mean what InDesign calls "Hyperlink". An example with 3 links is available at http://librelio-europe.s3.amazonaws.com/developer/ExempleInDesign.indd

> What should be the behaviour of the menu item? You say "create new Librelio links" but what should be the action in InDesign?

Create a new "Hyperlink", using the Librelio syntax.

**Comment by kinanu** [comment]
Ok. So you want to be able to edit the links of text frames (example with 3 links). I will fix that.

**Comment by libreliodev** [comment]
> So you want to be able to edit the links of text frames (example with 3 links)

Not only text frames, actually hyperlinks from any object.

**Comment by kinanu** [comment]
Ok.

**Comment by kinanu** [comment]
I have committed the fix. Now you can edit the hyperlinks of all objects. You can also create new hyperlinks by using the panel.

**Comment by libreliodev** [comment]
@kinanu Thanks for the great work.

> Now you can edit the hyperlinks of all objects

This looks good. However, no difference is made between video and slide shows. Videos use .mp4 or .mov files, slide shows use .png or .jpg files

> You can also create new hyperlinks by using the panel.

Sorry, I did not see how to use the panel to create new hyperlinks.

**Comment by kinanu** [comment]
> This looks good. However, no difference is made between video and slide shows. Videos use .mp4 or .mov files, slide shows use .png or .jpg files

That is correct. Problem is that now all objects can contain a hyperlink. How should the distinction be made? 

> Sorry, I did not see how to use the panel to create new hyperlinks

When you add a new object you can use the panel to enter a new hyperlink. Is this not working or what do you mean?=

**Comment by libreliodev** [comment]
> Problem is that now all objects can contain a hyperlink. How should the distinction be made?

It should be made based on the extension of the link:

> > Videos use .mp4 or .mov files, slide shows use .png or .jpg files

**Comment by libreliodev** [comment]
> When you add a new object you can use the panel to enter a new hyperlink. Is this not working or what do you mean?

We will need to improve this in the future, but it's OK for now.

**Comment by kinanu** [comment]
Ok. Lets assume we have a link which contains a movie (.mov extension). What should happen when you change the link (into for example: a link with extension .png or into a link without an extension)?

**Comment by libreliodev** [comment]
>  Lets assume we have a link which contains a movie (.mov extension). What should happen when you change the link (into for example: a link with extension .png or into a link without an extension)?

If the new link is with extension .png, display slide show options. If there is no extension, do not display any option

**Comment by kinanu** [comment]
I have committed a new version. Can you check and see if it is ok? Controls are now being enabled or disabled based on the extension.

**Comment by libreliodev** [comment]
Successfully tested!
