### ISSUE TITLE
Implement preview on iOS device via USB

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/indesign#11]
This should work in a similar way as the preview of folios from InDesign.

@kinanu : can you confirm this can be done using our plug-in? Do you know what are the requirements on the iOS viewer ?

**Comment by kinanu** [comment]
Sorry but this is not clear to me. What should the plugin do?

**Comment by libreliodev** [comment]
The plug-in should generate a pdf file (as specified in #7) and load it on the iOS device (with the images and videos  referenced in the enhancements) . 

This should work only from Mac. See http://helpx.adobe.com/digital-publishing-suite/help/preview-folios-articles.html#use_preview_on_device for a description of a similar existing functionality in InDesign;

**Comment by kinanu** [comment]
Yes. Exporting a pdf is possible from within the plugin. Copying the pdf to an iOS device and starting the Librelio app to preview the pdf should also be possible but this will require further investigation.

**Comment by libreliodev** [comment]
This is not going to work. We will use preview via Wifi later.
