### ISSUE TITLE
Implement video module

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/indesign#3]
There are different options for the video module that are specified by the link calling the module.

If the link contains waplay=auto (for example http://localhost/video.mov?waplay=auto), then the video should be launched automatically. If not, the video should be launched only when the user has tapped on the play button.

If the link contains warect=full (or example http://localhost/video.mov?warect=full), then the video should be launched in full screen. If not, the video should be launched only inside the region defined by the link in the pdf file.

**Comment by Web2PrintSolution** [comment]
1. You mentioned Acrobat, not InDesign, plugin
2. What kind of functionality should be implemented within InDesign
   May be I did not understand right but all mentioned issues are about PDF enhancements not exteneding InDesign functionality
3. Do you need in PDF builder that builds PDF with some specific enhancements?

**Comment by libreliodev** [comment]
@Web2PrintSolution Thanks for your comments. Here are the answers

> You mentioned Acrobat, not InDesign, plugin

That was a mistake, we corrected it. This project is about InDesign.

>  What kind of functionality should be implemented within InDesign
> May be I did not understand right but all mentioned issues are about PDF enhancements not exteneding InDesign functionality

You are right in a way, we are not willing to extend InDesign functionality, just to make it easy for our users to generate enhanced pdf files. In order to do so, we want to include a preview inside InDesign (issue #1) and to make it easy for the users to enter our specific links without learning our specific syntax (issues #2 and #3).

>  Do you need in PDF builder that builds PDF with some specific enhancements?

Yes, that's correct. Later on we will add some functionalities that will allow direct publishing from InDesign to our cloud server.

**Comment by libreliodev** [comment]
More precise specs about the video module are available at https://github.com/libreliodev/iOS/wiki/Video%20Module

cc @kinanu

**Comment by libreliodev** [comment]
@kinanu

The way this has been implemented so far is fine for the time being, but the various options for video should appear only if the link is with a .mov or .mp4 file

**Comment by libreliodev** [comment]
Successfully tested
