### ISSUE TITLE
Create installer for Plug In

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/indesign#8]
cc @kinanu @libreliorip

**Comment by libreliodev** [comment]
@kinanu When  trying to compile the project with the installer, the following error ocured

```
PhaseScriptExecution Run\ Script build/Librelio.build/Default/Release_Cocoa64.build/Script-F957086E15C90B3E00C95573.sh
    cd []/Librelio/project/cc2014/mac
    /bin/sh -c []/Librelio/project/cc2014/mac/build/Librelio.build/Default/Release_Cocoa64.build/Script-F957086E15C90B3E00C95573.sh

Resources are up-to-date.
installer/createInstaller.sh: line 4: ./ZXPSignCmd: No such file or directory
```

Please let us know if we missed something

**Comment by kinanu** [comment]
Hi,

I think I forgot to mention. I have updated the wiki (development setup). You have to download and install an additional tool to create the installer.

**Comment by libreliodev** [comment]
@kinanu Successfully compiled the plug-in after adding ZXPSignCmd as instructed in the wiki.

Got a warning message when installing the extension:

![screen shot 2014-09-01 at 08 25 22](https://cloud.githubusercontent.com/assets/3107052/4105408/0abd3cc2-31a9-11e4-9aaf-13a2209429ca.png)

Additionally, when launching InDesign, got an error

![screen shot 2014-09-01 at 09 20 26](https://cloud.githubusercontent.com/assets/3107052/4105410/23b29a56-31a9-11e4-880d-8394a0eeed91.png)

**Comment by kinanu** [comment]
Hi,

First warning is because of the certificate. I used a self signed certificate. This should be replaced by your certificate. I do not have the second error when I install the plugin but I will try this on a different machine.

**Comment by libreliodev** [comment]
@kinanu I realize that I used a wrong zxp file. Sorry about that, the installer works fine.
